services:
  db_postgres_p:
    container_name: postgres_prod
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: local
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  svelte-prod:
    container_name: svelte-prod
    build:
      context: .
      dockerfile: ./docker/Dockerfile.prod
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000

volumes:
  pgdata: